version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: transcriptionlogs
      POSTGRES_USER: transcriptor
      POSTGRES_PASSWORD: transcriptor_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U transcriptor -d transcriptionlogs"]
      interval: 10s
      timeout: 5s
      retries: 5

  angular-front:
    build:
      context: ./angular-front
    ports:
      - "4200:80"
    depends_on:
      - gatewayapi

  gatewayapi:
    build:
      context: ./api-gateway/gatewayapi
    ports:
      - "5000:8080"
    environment:
      - Database__Provider=PostgreSQL
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=transcriptionlogs;Username=transcriptor;Password=transcriptor_password
    depends_on:
      postgres:
        condition: service_healthy
      audio-streaming:
        condition: service_started
      transcriptor-python:
        condition: service_started

  audio-streaming:
    build:
      context: ./audio-streaming-service
    ports:
      - "9000:9000"

  transcriptor-python:
    build:
      context: ./transcriptor-python
    ports:
      - "8000:8000"

volumes:
  postgres_data:
